// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Archive          string
	ArchiveArtists   string
	ArchiveCircles   string
	ArchiveMagazines string
	ArchiveParodies  string
	ArchiveTags      string
	Artist           string
	Circle           string
	Magazine         string
	Parody           string
	Submission       string
	Tag              string
	UserFavorites    string
	Users            string
}{
	Archive:          "archive",
	ArchiveArtists:   "archive_artists",
	ArchiveCircles:   "archive_circles",
	ArchiveMagazines: "archive_magazines",
	ArchiveParodies:  "archive_parodies",
	ArchiveTags:      "archive_tags",
	Artist:           "artist",
	Circle:           "circle",
	Magazine:         "magazine",
	Parody:           "parody",
	Submission:       "submission",
	Tag:              "tag",
	UserFavorites:    "user_favorites",
	Users:            "users",
}
