// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Magazine is an object representing the database table.
type Magazine struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Slug string `boil:"slug" json:"slug" toml:"slug" yaml:"slug"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *magazineR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L magazineL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MagazineColumns = struct {
	ID   string
	Slug string
	Name string
}{
	ID:   "id",
	Slug: "slug",
	Name: "name",
}

var MagazineTableColumns = struct {
	ID   string
	Slug string
	Name string
}{
	ID:   "magazine.id",
	Slug: "magazine.slug",
	Name: "magazine.name",
}

// Generated where

var MagazineWhere = struct {
	ID   whereHelperint64
	Slug whereHelperstring
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"magazine\".\"id\""},
	Slug: whereHelperstring{field: "\"magazine\".\"slug\""},
	Name: whereHelperstring{field: "\"magazine\".\"name\""},
}

// MagazineRels is where relationship names are stored.
var MagazineRels = struct {
	Archives string
}{
	Archives: "Archives",
}

// magazineR is where relationships are stored.
type magazineR struct {
	Archives ArchiveSlice `boil:"Archives" json:"Archives" toml:"Archives" yaml:"Archives"`
}

// NewStruct creates a new relationship struct
func (*magazineR) NewStruct() *magazineR {
	return &magazineR{}
}

func (r *magazineR) GetArchives() ArchiveSlice {
	if r == nil {
		return nil
	}
	return r.Archives
}

// magazineL is where Load methods for each relationship are stored.
type magazineL struct{}

var (
	magazineAllColumns            = []string{"id", "slug", "name"}
	magazineColumnsWithoutDefault = []string{}
	magazineColumnsWithDefault    = []string{"id", "slug", "name"}
	magazinePrimaryKeyColumns     = []string{"id"}
	magazineGeneratedColumns      = []string{}
)

type (
	// MagazineSlice is an alias for a slice of pointers to Magazine.
	// This should almost always be used instead of []Magazine.
	MagazineSlice []*Magazine
	// MagazineHook is the signature for custom Magazine hook methods
	MagazineHook func(boil.Executor, *Magazine) error

	magazineQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	magazineType                 = reflect.TypeOf(&Magazine{})
	magazineMapping              = queries.MakeStructMapping(magazineType)
	magazinePrimaryKeyMapping, _ = queries.BindMapping(magazineType, magazineMapping, magazinePrimaryKeyColumns)
	magazineInsertCacheMut       sync.RWMutex
	magazineInsertCache          = make(map[string]insertCache)
	magazineUpdateCacheMut       sync.RWMutex
	magazineUpdateCache          = make(map[string]updateCache)
	magazineUpsertCacheMut       sync.RWMutex
	magazineUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var magazineAfterSelectHooks []MagazineHook

var magazineBeforeInsertHooks []MagazineHook
var magazineAfterInsertHooks []MagazineHook

var magazineBeforeUpdateHooks []MagazineHook
var magazineAfterUpdateHooks []MagazineHook

var magazineBeforeDeleteHooks []MagazineHook
var magazineAfterDeleteHooks []MagazineHook

var magazineBeforeUpsertHooks []MagazineHook
var magazineAfterUpsertHooks []MagazineHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Magazine) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Magazine) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Magazine) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Magazine) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Magazine) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Magazine) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Magazine) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Magazine) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Magazine) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range magazineAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMagazineHook registers your hook function for all future operations.
func AddMagazineHook(hookPoint boil.HookPoint, magazineHook MagazineHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		magazineAfterSelectHooks = append(magazineAfterSelectHooks, magazineHook)
	case boil.BeforeInsertHook:
		magazineBeforeInsertHooks = append(magazineBeforeInsertHooks, magazineHook)
	case boil.AfterInsertHook:
		magazineAfterInsertHooks = append(magazineAfterInsertHooks, magazineHook)
	case boil.BeforeUpdateHook:
		magazineBeforeUpdateHooks = append(magazineBeforeUpdateHooks, magazineHook)
	case boil.AfterUpdateHook:
		magazineAfterUpdateHooks = append(magazineAfterUpdateHooks, magazineHook)
	case boil.BeforeDeleteHook:
		magazineBeforeDeleteHooks = append(magazineBeforeDeleteHooks, magazineHook)
	case boil.AfterDeleteHook:
		magazineAfterDeleteHooks = append(magazineAfterDeleteHooks, magazineHook)
	case boil.BeforeUpsertHook:
		magazineBeforeUpsertHooks = append(magazineBeforeUpsertHooks, magazineHook)
	case boil.AfterUpsertHook:
		magazineAfterUpsertHooks = append(magazineAfterUpsertHooks, magazineHook)
	}
}

// OneG returns a single magazine record from the query using the global executor.
func (q magazineQuery) OneG() (*Magazine, error) {
	return q.One(boil.GetDB())
}

// One returns a single magazine record from the query.
func (q magazineQuery) One(exec boil.Executor) (*Magazine, error) {
	o := &Magazine{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for magazine")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Magazine records from the query using the global executor.
func (q magazineQuery) AllG() (MagazineSlice, error) {
	return q.All(boil.GetDB())
}

// All returns all Magazine records from the query.
func (q magazineQuery) All(exec boil.Executor) (MagazineSlice, error) {
	var o []*Magazine

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Magazine slice")
	}

	if len(magazineAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Magazine records in the query using the global executor
func (q magazineQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// Count returns the count of all Magazine records in the query.
func (q magazineQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count magazine rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q magazineQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// Exists checks if the row exists in the table.
func (q magazineQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if magazine exists")
	}

	return count > 0, nil
}

// Archives retrieves all the archive's Archives with an executor.
func (o *Magazine) Archives(mods ...qm.QueryMod) archiveQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"archive_magazines\" on \"archive\".\"id\" = \"archive_magazines\".\"archive_id\""),
		qm.Where("\"archive_magazines\".\"magazine_id\"=?", o.ID),
	)

	return Archives(queryMods...)
}

// LoadArchives allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (magazineL) LoadArchives(e boil.Executor, singular bool, maybeMagazine interface{}, mods queries.Applicator) error {
	var slice []*Magazine
	var object *Magazine

	if singular {
		object = maybeMagazine.(*Magazine)
	} else {
		slice = *maybeMagazine.(*[]*Magazine)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &magazineR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &magazineR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.Select("\"archive\".\"id\", \"archive\".\"path\", \"archive\".\"created_at\", \"archive\".\"updated_at\", \"archive\".\"published_at\", \"archive\".\"title\", \"archive\".\"slug\", \"archive\".\"pages\", \"archive\".\"size\", \"archive\".\"expunged\", \"archive\".\"source\", \"archive\".\"submission_id\", \"archive\".\"redirect_id\", \"a\".\"magazine_id\""),
		qm.From("\"archive\""),
		qm.InnerJoin("\"archive_magazines\" as \"a\" on \"archive\".\"id\" = \"a\".\"archive_id\""),
		qm.WhereIn("\"a\".\"magazine_id\" in ?", args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load archive")
	}

	var resultSlice []*Archive

	var localJoinCols []int64
	for results.Next() {
		one := new(Archive)
		var localJoinCol int64

		err = results.Scan(&one.ID, &one.Path, &one.CreatedAt, &one.UpdatedAt, &one.PublishedAt, &one.Title, &one.Slug, &one.Pages, &one.Size, &one.Expunged, &one.Source, &one.SubmissionID, &one.RedirectID, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for archive")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice archive")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on archive")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for archive")
	}

	if len(archiveAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Archives = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &archiveR{}
			}
			foreign.R.Magazines = append(foreign.R.Magazines, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.Archives = append(local.R.Archives, foreign)
				if foreign.R == nil {
					foreign.R = &archiveR{}
				}
				foreign.R.Magazines = append(foreign.R.Magazines, local)
				break
			}
		}
	}

	return nil
}

// AddArchivesG adds the given related objects to the existing relationships
// of the magazine, optionally inserting them as new records.
// Appends related to o.R.Archives.
// Sets related.R.Magazines appropriately.
// Uses the global database handle.
func (o *Magazine) AddArchivesG(insert bool, related ...*Archive) error {
	return o.AddArchives(boil.GetDB(), insert, related...)
}

// AddArchives adds the given related objects to the existing relationships
// of the magazine, optionally inserting them as new records.
// Appends related to o.R.Archives.
// Sets related.R.Magazines appropriately.
func (o *Magazine) AddArchives(exec boil.Executor, insert bool, related ...*Archive) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"archive_magazines\" (\"magazine_id\", \"archive_id\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.DebugMode {
			fmt.Fprintln(boil.DebugWriter, query)
			fmt.Fprintln(boil.DebugWriter, values)
		}
		_, err = exec.Exec(query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &magazineR{
			Archives: related,
		}
	} else {
		o.R.Archives = append(o.R.Archives, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &archiveR{
				Magazines: MagazineSlice{o},
			}
		} else {
			rel.R.Magazines = append(rel.R.Magazines, o)
		}
	}
	return nil
}

// SetArchivesG removes all previously related items of the
// magazine replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Magazines's Archives accordingly.
// Replaces o.R.Archives with related.
// Sets related.R.Magazines's Archives accordingly.
// Uses the global database handle.
func (o *Magazine) SetArchivesG(insert bool, related ...*Archive) error {
	return o.SetArchives(boil.GetDB(), insert, related...)
}

// SetArchives removes all previously related items of the
// magazine replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Magazines's Archives accordingly.
// Replaces o.R.Archives with related.
// Sets related.R.Magazines's Archives accordingly.
func (o *Magazine) SetArchives(exec boil.Executor, insert bool, related ...*Archive) error {
	query := "delete from \"archive_magazines\" where \"magazine_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeArchivesFromMagazinesSlice(o, related)
	if o.R != nil {
		o.R.Archives = nil
	}

	return o.AddArchives(exec, insert, related...)
}

// RemoveArchivesG relationships from objects passed in.
// Removes related items from R.Archives (uses pointer comparison, removal does not keep order)
// Sets related.R.Magazines.
// Uses the global database handle.
func (o *Magazine) RemoveArchivesG(related ...*Archive) error {
	return o.RemoveArchives(boil.GetDB(), related...)
}

// RemoveArchives relationships from objects passed in.
// Removes related items from R.Archives (uses pointer comparison, removal does not keep order)
// Sets related.R.Magazines.
func (o *Magazine) RemoveArchives(exec boil.Executor, related ...*Archive) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"archive_magazines\" where \"magazine_id\" = $1 and \"archive_id\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err = exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeArchivesFromMagazinesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Archives {
			if rel != ri {
				continue
			}

			ln := len(o.R.Archives)
			if ln > 1 && i < ln-1 {
				o.R.Archives[i] = o.R.Archives[ln-1]
			}
			o.R.Archives = o.R.Archives[:ln-1]
			break
		}
	}

	return nil
}

func removeArchivesFromMagazinesSlice(o *Magazine, related []*Archive) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.Magazines {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.Magazines)
			if ln > 1 && i < ln-1 {
				rel.R.Magazines[i] = rel.R.Magazines[ln-1]
			}
			rel.R.Magazines = rel.R.Magazines[:ln-1]
			break
		}
	}
}

// Magazines retrieves all the records using an executor.
func Magazines(mods ...qm.QueryMod) magazineQuery {
	mods = append(mods, qm.From("\"magazine\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"magazine\".*"})
	}

	return magazineQuery{q}
}

// FindMagazineG retrieves a single record by ID.
func FindMagazineG(iD int64, selectCols ...string) (*Magazine, error) {
	return FindMagazine(boil.GetDB(), iD, selectCols...)
}

// FindMagazine retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMagazine(exec boil.Executor, iD int64, selectCols ...string) (*Magazine, error) {
	magazineObj := &Magazine{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"magazine\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, magazineObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from magazine")
	}

	if err = magazineObj.doAfterSelectHooks(exec); err != nil {
		return magazineObj, err
	}

	return magazineObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Magazine) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Magazine) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no magazine provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(magazineColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	magazineInsertCacheMut.RLock()
	cache, cached := magazineInsertCache[key]
	magazineInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			magazineAllColumns,
			magazineColumnsWithDefault,
			magazineColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(magazineType, magazineMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(magazineType, magazineMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"magazine\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"magazine\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into magazine")
	}

	if !cached {
		magazineInsertCacheMut.Lock()
		magazineInsertCache[key] = cache
		magazineInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Magazine record using the global executor.
// See Update for more documentation.
func (o *Magazine) UpdateG(columns boil.Columns) error {
	return o.Update(boil.GetDB(), columns)
}

// Update uses an executor to update the Magazine.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Magazine) Update(exec boil.Executor, columns boil.Columns) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(columns, nil)
	magazineUpdateCacheMut.RLock()
	cache, cached := magazineUpdateCache[key]
	magazineUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			magazineAllColumns,
			magazinePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update magazine, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"magazine\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, magazinePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(magazineType, magazineMapping, append(wl, magazinePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update magazine row")
	}

	if !cached {
		magazineUpdateCacheMut.Lock()
		magazineUpdateCache[key] = cache
		magazineUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q magazineQuery) UpdateAllG(cols M) error {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q magazineQuery) UpdateAll(exec boil.Executor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for magazine")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o MagazineSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MagazineSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), magazinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"magazine\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, magazinePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in magazine slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Magazine) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Magazine) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no magazine provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(magazineColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	magazineUpsertCacheMut.RLock()
	cache, cached := magazineUpsertCache[key]
	magazineUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			magazineAllColumns,
			magazineColumnsWithDefault,
			magazineColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			magazineAllColumns,
			magazinePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert magazine, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(magazinePrimaryKeyColumns))
			copy(conflict, magazinePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"magazine\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(magazineType, magazineMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(magazineType, magazineMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert magazine")
	}

	if !cached {
		magazineUpsertCacheMut.Lock()
		magazineUpsertCache[key] = cache
		magazineUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteG deletes a single Magazine record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Magazine) DeleteG() error {
	return o.Delete(boil.GetDB())
}

// Delete deletes a single Magazine record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Magazine) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Magazine provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), magazinePrimaryKeyMapping)
	sql := "DELETE FROM \"magazine\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from magazine")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

func (q magazineQuery) DeleteAllG() error {
	return q.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all matching rows.
func (q magazineQuery) DeleteAll(exec boil.Executor) error {
	if q.Query == nil {
		return errors.New("models: no magazineQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from magazine")
	}

	return nil
}

// DeleteAllG deletes all rows in the slice.
func (o MagazineSlice) DeleteAllG() error {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MagazineSlice) DeleteAll(exec boil.Executor) error {
	if len(o) == 0 {
		return nil
	}

	if len(magazineBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), magazinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"magazine\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, magazinePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from magazine slice")
	}

	if len(magazineAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Magazine) ReloadG() error {
	if o == nil {
		return errors.New("models: no Magazine provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Magazine) Reload(exec boil.Executor) error {
	ret, err := FindMagazine(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MagazineSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty MagazineSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MagazineSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MagazineSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), magazinePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"magazine\".* FROM \"magazine\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, magazinePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MagazineSlice")
	}

	*o = slice

	return nil
}

// MagazineExistsG checks if the Magazine row exists.
func MagazineExistsG(iD int64) (bool, error) {
	return MagazineExists(boil.GetDB(), iD)
}

// MagazineExists checks if the Magazine row exists.
func MagazineExists(exec boil.Executor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"magazine\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if magazine exists")
	}

	return exists, nil
}
